# Chromatic action from https://www.chromatic.com/docs/github-actions

# Workflow name
name: "chromatic"

on:
  # despite the name, this is triggered on both isuse comments *and* PR comments. We're only interested in PR comments for this Action.
  # issue_comment:
  #   types: [created]
  push

# List of jobs
jobs:
  visual-testing:
    # Operating System
    runs-on: ubuntu-latest

    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - uses: actions/setup-node@v1
        with:
          node-version: "14.15.x"

      - name: Install package dependencies for private-github-action-scripts
        run: |
          yarn workspace private-github-action-scripts install --frozen-lockfile

      - run: yarn workspace private-github-action-scripts should-we-run-chromatic
        id: should-we-run-chromatic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          PR_URL: ${{ github.event.issue.pull_request.url }}

      - name: debug should we run chromatic
        run: echo "Should we run chromatic ${{ steps.should-we-run-chromatic.outputs.RESULT }}"

      - run: |
          echo "runChromatic=${runChromatic}" >> $GITHUB_ENV
        env:
          runChromatic: ${{ steps.should-we-run-chromatic.outputs.RESULT }}

      - uses: actions/cache@v2 # use of cache for node_modules saves usually > 1min of build time
        if: ${{ env.runChromatic == 'true' }}
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-

      - name: Install package dependencies for Chromatic build
        if: ${{ env.runChromatic == 'true' }}
        run: |
          yarn install --frozen-lockfile

      # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        if: ${{ env.runChromatic == 'true' }}
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: master # 👈 Auto accept master builds (why https://www.chromatic.com/docs/github-actions#github-squashrebase-merge-and-the-main-branch)
